name: Build app

on:
  pull_request:
    types:
      - closed

jobs:
  run-checks:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/pull_request_checks.yml

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: run-checks
    strategy:
      matrix:
        node: [20.x]
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.TEST_MOBILE_TOKEN }}

      - name: Setup EAS local builds
        run: yarn global add eas-cli-local-build-plugin

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: |
          eas build --local \
            --non-interactive \
            --output=./app-build \
            --platform=android \
            --profile=preview

      - name: Rename build directory
        run: mv app-build Test-Fidelizi-by-Mayro.apk

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Test-Fidelizi-by-Mayro
          path: Test-Fidelizi-by-Mayro.apk